### ISSUE TITLE
Istio/コードブロックのコマンドと実行結果を分ける

### ISSUE THREAD

**Issue by Himalayan-wildcat** [cloudnativedaysjp/cndt2023-handson#157]
## 概要
11/14の1回目の通し会でコードブロック仕様、書き方に関して統一することになった。Istio/Istio ambient mesh chapterで修正が必要な、または確認が必要な箇所は下記のとおり。

### コマンドと実行結果を分ける

(before)
```
some command

some outputs
```
(after)
```
some command
```
```
# 実行結果
some outputs
```

### 言語識別子はshにする
これは問題なさそうだが、念のため確認。

**Comment by Himalayan-wildcat** [comment]
@mikiT 
変更ありがとうございます。:bow:
一点お伺いで恐縮です。Istio/Istio ambient mesh chapter双方で、`出力結果例`が残っているところが何箇所か見受けられるのですが、これは何か意図がありますでしょうか？

**Comment by mikiT** [comment]
これ気づいてなかった。ごめんなさい〜
