### ISSUE TITLE
opentelemetryのChapterの追加・修正

### ISSUE THREAD

**Issue by TatsukiMinami** [cloudnativedaysjp/cndt2023-handson#260]
LokiとPyroscopeなどと連携するのがあれば、各プロダクトのところで変更対応する？

**Comment by mongamae-nioh** [comment]
[issues-260-otel-contents-update](https://github.com/cloudnativedaysjp/cnd-handson/tree/issues-260-otel-contents-update)で以下を実施
- chart versionを最新化
- READMEの誤記修正や文言統一
